= Obtain OpenStreetMap-Data and use it with QGIS 3
OpenSchoolMaps.ch - Free learning materials for free geodata and maps
:xrefstyle: short
:imagesdir: ../../../bilder/
include::../../../snippets/suppress_title_page.adoc[]

A guide for the interested, for pupils and for instructors/teachers

== Overview

.Goal
The goal of this guide is to show how to get OpenStreetMap data and use it in QGIS 3.

.Audience
Anyone who is interested in creating their own map (online, as a printable plan) 
and in analysing geodata.

.Scheduling
This worksheet requires different amounts of time depending on your previous 
knowledge, since you can skip individual sections if you are already familiar 
with the topic in question.

.Structure
The following topics will be covered:

* Introduction with explanations of OpenStreetMap and geoinformation 
systems as well as common file formats
* Extract OpenStreetMap data with Overpass
* Import OpenStreetMap data directly into QGIS with QuickOSM plugin
* Various web tools for downloading OpenStreetMap data
* Merging Polygon Layers with Point Layers in QGIS
* Filtering or rule-based display of objects with QGIS

We recommend at least reading the introduction and extracting the 
chapter OpenStreetMap data with overpass.

[NOTE]
====
This tutorial is about using existing data from OpenStreetMap. 
If you want to record data yourself, you can use the worksheets 
"Edit OpenStreetMap" and "Create a thematic online map with uMap" 
as well as https://learnosm.org/de/ for more information.
====

== Introduction

The data from OpenStreetMap comes in different data formats.
Therefore we will first explain some of these file formats in more detail.

=== OpenStreetMap and geoinformation systems

The geometry of the objects in OpenStreetMap (OSM) are stored internally 
as topological structures (nodes, ways). 
And the object attributes as tags (key-value pairs) only partially structured. 
This data schema, which can be extended at will, must first be converted for 
geoinformation systems (GIS) and their formats. 
There is no single GIS data schema for OSM. 
Hardly any export from OSM is therefore the same as the other.

=== File formats

Basically, one can distinguish between OSM's own and analyzable GIS formats.

* OSM-specific formats are mainly OSM XML, and OSM PBF.
* GIS compatible formats are GeoJSON, Geopackage (and related: MBTile/SQLite), 
Shapefiles, GeoJSON (TopoJSON).
* Other GIS vector formats are: KML and GPX for GPS data exchange.
* Other formats that cannot be analysed further are image/raster formats such as PNG, JPEG, SVG and PDF.

The following describes various methods for importing OpenStreetMap data into QGIS. 
The first method works with Overpass-Turbo, a web service for querying OpenStreetMap data. 
We recommend that you look at this method as it is the most efficient of all the methods presented. 
The second method is based on QuickOSM, a plugin for QGIS in which queries can be created. 
If you've read or read the overpass turbo section, you can consider it optional with QuickOSM. 

After the two inport methods further tools are introduced, for example the HOT Export Tool or OSMaxx. 

Finally, you will learn how to merge different layers in QGIS. 
This chapter is referred to at the end of the remaining chapters, so you'll come there for or after.

== Extract OpenStreetMap data with Overpass


