variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/build:$CI_COMMIT_REF_SLUG

image: $BUILD_IMAGE

stages:
- prebuild
- build
- pages


######################################################################
# prebuild
######################################################################

# Builds the Docker image $BUILD_IMAGE for subsequent build steps.
build_image:
  stage: prebuild
  image: docker:latest
  services:
    - docker:dind  # required for Docker-in-Docker on gitlab.com
  only:
    changes:
      - docker.build/*
      - .gitlab-ci.yml
      - pages/requirements.txt
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - mv pages/requirements.txt docker.build
    - cd docker.build
    - docker build --tag $BUILD_IMAGE -f Dockerfile.build .
    - docker push $BUILD_IMAGE


######################################################################
# build
######################################################################

PDFs:
  stage: build
  variables:
    LANG: de_CH.utf8
  tags:
  - docker
  script:
  - ./build.py
  artifacts:
    expire_in: 3 mos
    paths:
    - lehrmittel/**/*.pdf
    - lehrmittel/**/**/*.pdf
    - lehrmittel/OpenStreetMap Tagging Cheatsheet.docx
    - lehrmittel/OpenStreetMap Tagging Cheatsheet.pdf

QGIS excercise data:
  stage: build
  script:
  # Dummy script,
  # because we only need to collect some files from the Git repo as artifacts.
  - "true"
  artifacts:
    name: "Daten_Leitprogramm_QGIS"
    expire_in: 3 mos
    paths:
    - lehrmittel/einfuehrung_in_qgis/daten_leitprogramm_qgis/

autobahn excercise data:
  stage: build
  script:
  # Dummy script,
  # because we only need to collect some files from the Git repo as artifacts.
  - "true"
  artifacts:
    name: "Daten_autobahn"
    expire_in: 3 mos
    paths:
    - lehrmittel/geodaten-analyse_mit_qgis/vektordaten-analyse_mit_qgis/vektordaten-analyse_mit_qgis_autobahn/

gaemsen excercise data:
  stage: build
  script:
  # Dummy script,
  # because we only need to collect some files from the Git repo as artifacts.
  - "true"
  artifacts:
    name: "Input-Daten_gaemsen"
    expire_in: 3 mos
    paths:
    - lehrmittel/geodaten-analyse_mit_qgis/rasterdaten-analyse_mit_qgis/rasterdaten-analyse_mit_qgis_gaemsen_daten/
    
superset csv data:
  stage: build
  script:
  # Dummy script,
  # because we only need to collect some files from the Git repo as artifacts.
  - "true"
  artifacts:
    name: "Superset-Datentabellen"
    expire_in: 3 mos
    paths:
    - lehrmittel/einfuehrung_in_apache_superset/files/


######################################################################
# pages
######################################################################

pages:
  stage: pages
  script:
  - cd pages/
  - ln -s /opt/pelican-{themes,plugins} .  # Pulls in repos provided by build image
  - pelican --fatal errors -s publishconf.py
  - mv .well-known/ public/.well-known
  - mv public/ ..
  only:
    refs:
      - master
  artifacts:
    paths:
    - public/
