image: asciidoctor/docker-asciidoctor

pages:
  script:
  - apk update
  - apk add git py2-pip
  - git clone --depth 1 https://github.com/getpelican/pelican-plugins
  - git clone --depth 1 https://github.com/getpelican/pelican-themes.git
  - pip install -r requirements.txt
  - pelican -s publishconf.py
  artifacts:
    paths:
    - public/
