PDFs:
  image: asciidoctor/docker-asciidoctor:latest
  stage: build
  variables:
    LANG: de_CH.utf8
  tags:
  - docker
  script:
  - set -e
  - for f in $(find ./lehrmittel/ -name '*.adoc');
    do
      asciidoctor-pdf
        --attribute icons=font
        $f;
    done
  - for f in $(grep -rl 'def::show_solutions\[' lehrmittel/ | grep '.adoc$');
    do
      asciidoctor-pdf
        --attribute icons=font
        --attribute show_solutions
        $f
        -o ${f%.*}_solutions.pdf;
    done
  artifacts:
    expire_in: 3 mos
    paths:
    - lehrmittel/**/*.pdf
    - lehrmittel/**/**/*.pdf
