= OSM.org comme visualiseur de cartes pour les enseignants
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*Une feuille de travail pour les enseignants*

== Aperçu

.Ziel
Après avoir édité la feuille de travail correspondante, les SuS peuvent utiliser openstreetmap.org pour visualiser la carte OpenStreetMap, rechercher des lieux et des choses sur la carte, utiliser la fonction de routage et ajouter des "notes" à OpenStreetMap pour améliorer les données cartographiques.

.Zielgruppe
SuS dans le curriculum 21 cycle 2 ou 3 (4ème à 9ème année scolaire)

.Planification
* Feuille de travail "Apprendre à connaître OSM.org" : 20 minutes
* Feuille de travail "Utiliser OSM.org au quotidien" : 10 minutes
* Feuille de travail OpenStreetMap Examine Data : 15 minutes

La feuille de travail devrait prendre environ une leçon (45 minutes).

== Préparation

Le SuS doit disposer d'un *atlas physique ou d'une carte papier*, et si possible aussi d'un globe terrestre.

Comme alternative à un globe terrestre, le programme informatique "Marble" peut être utilisé.

Pour éditer la feuille de travail, les SuS nécessitent un *navigateur Web* avec *accès Internet* (au moins à https://openstreetmap.org).

include::../../../snippets/kontaktinformationen.adoc[]

include::../../../snippets/quellenangabe.adoc[]
