= Lehrpersonen-Informationen zum Arbeitsblatt "OSM.org als Karten-Viewer"
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*Ein Arbeitsblatt für Lehrpersonen*

== Übersicht

.Ziel
Nach Bearbeiten des zugehörigen Arbeitsblattes sind die SuS in der Lage, openstreetmap.org zum Betrachten der OpenStreetMap-Karte zu verwenden, Orte und Dinge auf der Karte zu suchen, die Routing-Funktion zu benutzen und "Notizen" in OpenStreetMap einzutragen um bei der Verbesserung der Kartendaten zu helfen.

.Zielgruppe
SuS im Lehrplan-21-Zyklus 2 oder 3 (4. bis 9. Schuljahr)

.Zeitplanung
* Arbeitsblatt "Webseite OSM.org kennenlernen": 20 Minuten
* Arbeitsblatt "Webseite OSM.org im Alltag nutzen": 10 Minuten
* Arbeitsblatt "OpenStreetMap-Daten untersuchen": 15 Minuten

Das Arbeitsblatt sollte etwa eine Lektion (45 Minuten) dauern.

== Vorbereitung
Die SuS sollten einen *physischen Atlas oder eine Papierkarte* zur Verfügung haben, und nach Möglichkeit auch einen Globus.

Alternativ zu einem Globus kann das Computerprogramm "Marble" verwendet werden.

Die SuS benötigen für das Bearbeiten des Arbeitsblatts einen *Webbrowser* mit *Internet-Zugang* (mindestens zu https://openstreetmap.org).

include::../../../snippets/kontaktinformationen.adoc[]

include::../../../snippets/quellenangabe.adoc[]
