= Teacher information on the "OSM.org as a map viewer" worksheet
OpenSchoolMaps.ch -- Free learning materials for free geodata and maps
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*A worksheet for teachers*
ifdef::show_solutions[- *SOLUTIONS*]

== Synopsis

.Aim
After editing the corresponding worksheet, students should be able to use openstreetmap.org to view the OpenStreetMap, find places and things on the map, use the routing function and enter "notes" in OpenStreetMap to help improve the map data.

.Target Group
Students in Lehrplan 21 Zyklus 2 or 3 (4th to 9th school year)

.Time Schedule
* "Get to know the OSM.org website" worksheet: 20 minutes	
* "Using the OSM.org website in everyday life" worksheet: 10 minutes
* "Examine OpenStreetMap data" worksheet: 15 Minuten

The total time taken should be about one lesson (45 minutes).

== Prearrangement

The students should have a *physical atlas or a physical map*, and if possible also a globe.

As an alternative to a globe, the computer program "Marble" can be used.

The students require a *web browser* with *Internet access* (at least to https://openstreetmap.org) for them to work on the worksheet.

<<<

== Additional Task

=== Web-Competence

How did the content of the browser address bar change when you went to `osm.org`?

ifdef::show_solutions[]
`osm.org` was automatically replaced by something like `https://www.openstreetmap.org/#map=8/46.825/8.224`.
endif::show_solutions[]

Can you explain the individual parts of the address?

ifdef::show_solutions[]

* `https://`: The protocol used. HTTP (Hypertext transfer protocol) is the way Internet pages and other data are transmitted on the World Wide Web. The `s` (Secure) at the end indicates that the connection to the website is encrypted.

* `openstreetmap.org`: The main domain of the OpenStreetMap project. The extension (="top-level domain") `.org` was chosen to emphasize that this is a volunteer project, not a commercial venture like much of `.com`. `osm.org` is another domain of the project, which forwards to the corresponding `openstreetmap.org` pages. This saves you typing.

* `www.`: A sub-domain indicating that it is a website on the World Wide Web (WWW). Somewhat redundant, as this is already implied by the HTTP protocol and the globally accessible domain.

* `#map=8/46.825/8.224`: DThe map section. This includes:

  * `8`: The "zoom level". The larger this number, the closer the view is zoomed.

  * `46.825`: The latitude in WGS-84 coordinates as decimal number (degrees with decimal places)

  * `8.224`: The geographic longitude in WGS-84 coordinates as decimal number (degrees with decimal places)
endif::show_solutions[]

.Suggestion
In geography lessons it is often common to enter angular coordinates in degrees, minutes and seconds. Use this opportunity to practice the conversion between decimal fraction and the degree-minute-second system. For example, coordinate data from the register of an atlas can be translated into OpenStreetMap URLs.

=== Task for advanced students / higher classes
Zoom out so far that you can see whole continents or even the whole earth. Then move the map north or south without zooming. Why does the scale change?


include::../../../snippets/kontaktinformationen.adoc[]

include::../../../snippets/quellenangabe.adoc[]
