= Lehrpersonen-Informationen zur "Einführung in QGIS 3 und GIS"
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*Ein Informationsblatt für Interessierte und Lehrpersonen*

== Übersicht

.Ziel
Nach Bearbeiten des zugehörigen Arbeitsblattes sind Sie / die SuS in der Lage, die Grundfunktionen von QGIS zu verwenden.

.Zielgruppen
* SuS im Lehrplan-21-Zyklus 2 oder 3 (4. bis 9. Schuljahr) begleitet von einer Lehrperson
* Interessierte (Selbststudium)

.Zeitplanung
* Für jedes Kapitel sollte ca. 1 Stunde eingerechnet werden.

== Vorbereitung
Sie / die SuS sollten das Programm QGIS Version 3.x auf ihrem Rechner installiert haben.

Die SuS benötigen für das Bearbeiten des Arbeitsblatts einen *Webbrowser* mit *Internet-Zugang*.

== Chapter test questions

See chapter "Chapter test" at the end of the corresponding chapter or worksheet.

Chapter 1 What is a  Geographic Information System?

* Question 1 What is a GIS?
* Question 2 What tools do you have to navigate on the map?
* Question 3 In which subject would GIS be useful?  

Chapter 2 What is Geodata? 

* Question 1 What do the raster and vector format look like?  
* Question 2 What does the term geographical data mean?
* Question 3 What is the difference between WMS layer and vector data layer?  

Chapter 3 Data collection and Management

* Question 1 What two ways do you know of storing vector data?  
* Question 2 Describe the structure of a table.
* Question 3 What must a text file contain in order to be visible in the map window?  
* Question 4 What possibilities do you have to get the different data?  

Chapter 4 Data Analysis

* Question 1 What is the difference between query and manipulation?  
* Question 2 Creating an SQL query  
* Question 3 Combination of SQL Queries  

Chapter 5 Presentation of Geographic Information 

* Question 1 Creating and exporting a map  
* Question 2 Evaluate map 

Noch Fragen?
Wenden Sie sich an QGIS (https://www.qgis.org) oder Stefan Keller (sfkeller@hsr.ch)!

include::../../../snippets/quellenangabe.adoc[]
