= Teacher information on "Introduction to QGIS 3 and GIS
OpenSchoolMaps.ch -- Free learning materials for free geodata and maps
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*An information sheet for interested people and teachers*

== Overview

.Objective
After completing the corresponding worksheet, you/the students will be able to use the basic functions of QGIS.

.Target group
* Students in curriculum 21 cycle 2 or 3 (4th to 9th school year) supported by a teacher
* Interested (self-study)

.Scheduling
* Each chapter should take about 1 hour.

== Preparation
You / the students should have installed the program QGIS Version 3.x on your computer.

The students need a *Webbrowser* with *internet access* to complete the worksheets.

== Chapter test questions

See chapter "Chapter test" at the end of the corresponding chapter or worksheet.

Chapter 1 What is a  Geographic Information System?

* Question 1 What is a GIS?
* Question 2 What tools do you have to navigate on the map?
* Question 3 In which subject would GIS be useful?  

Chapter 2 What is Geodata? 

* Question 1 What do the raster and vector format look like?  
* Question 2 What does the term geographical data mean?
* Question 3 What is the difference between WMS layer and vector data layer?  

Chapter 3 Data collection and Management

* Question 1 What two ways do you know of storing vector data?  
* Question 2 Describe the structure of a table.
* Question 3 What must a text file contain in order to be visible in the map window?  
* Question 4 What possibilities do you have to get the different data?  

Chapter 4 Data Analysis

* Question 1 What is the difference between query and manipulation?  
* Question 2 Creating an SQL query  
* Question 3 Combination of SQL Queries  

Chapter 5 Presentation of Geographic Information 

* Question 1 Creating and exporting a map  
* Question 2 Evaluate map 

Any questions?
Turn to QGIS (https://www.qgis.org) or Stefan Keller (sfkeller@hsr.ch)!

include::../../../snippets/quellenangabe.adoc[]
