= Tâches supplémentaires
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*Une feuille de travail*
ifdef::show_solutions[- *LÖSUNGEN*]

== Missions additionnelles

=== Expertise web

Comment le contenu de la barre d'adresse du navigateur a-t-il changé lorsque tu es allé sur `osm.org`?

ifdef::show_solutions[]
`osm.org' a été automatiquement remplacé par quelque chose comme `https://www.openstreetmap.org/#map=8/46.825/8.224'.
endif::show_solutions[]

Peux-tu expliquer les différentes parties de l'adresse ?

ifdef::show_solutions[]

* `https://`: Das verwendete Protokoll. HTTP (Hypertext transfer protocol) ist die Art und Weise wie Internet-Seiten und sonstige Daten im World Wide Web übertragen werden. Das `s` am Ende zeigt an, dass die Verbindung zur Website verschüsselt erfolgt.

* `openstreetmap.org`: Die Haupt-Domain des OpenStreetMap-Projekts. Die Endung (="Top-Level-Domain") `.org` wurde gewählt, um zu betonen, dass es sich um ein Projekt von Freiwilligen handelt, nicht um ein Kommerzielles unterfangen wie vieles unter `.com`. `osm.org` ist eine weitere Domain des Projekts, die auf die entsprechenden `openstreetmap.org`-Seiten weiterleitet. So kann man sich Tipparbeit sparen.

* `www.`: Eine Sub-Domain, die anzeigt, dass es sich um eine Website im World Wide Web (WWW) handelt. Etwas redundant, da das durch das HTTP-Protokoll und die global erreichbare Domain bereits impliziert ist.

* `#map=8/46.825/8.224`: Der Karten-Ausschnitt. Dabei ist:

  * `8`: Das "Zoom-Level". Je grösser diese Zahl, um so "näher ran" gezoomt ist die Ansicht.

  * `46.825`: Die geografische Breite in WGS-84-Koordinaten als Dezimal-Zahl (Grad mit Nachkommastellen)

  * `8.224`: Die geografische Länge in WGS-84-Koordinaten als Dezimal-Zahl (Grad mit Nachkommastellen)

.Dynamisation
Dans les leçons de géographie, il est souvent courant de spécifier les coordonnées angulaires en degrés, minutes et secondes. Profite de cette occasion pour pratiquer la conversion entre la fraction décimale et le système degré-minute-seconde. Par exemple, les informations de coordonnées du registre d'un atlas peuvent être traduites en URL OpenStreetMap.

endif::show_solutions[]

=== Tâche pour les SuS avancés / classes supérieures

Fais un zoom arrière jusqu'à ce que tu puisses voir des continents entiers ou même la terre entière. Puis déplace la carte vers le nord ou le sud sans zoomer. Pourquoi cela change-t-il l'échelle?

include::../../../snippets/quellenangabe.adoc[]
