= Tâches supplémentaires
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:imagesdir: ../../../bilder/
include::../../../snippets/lang/de.adoc[]
include::../../../snippets/suppress_title_page.adoc[]

*Une feuille de travail*
ifdef::show_solutions[- *LÖSUNGEN*]

== Missions additionnelles

=== Expertise web

Comment le contenu de la barre d'adresse du navigateur a-t-il changé lorsque tu es allé sur `osm.org`?

ifdef::show_solutions[]
`osm.org' a été automatiquement remplacé par quelque chose comme `https://www.openstreetmap.org/#map=8/46.825/8.224'.
endif::show_solutions[]

Peux-tu expliquer les différentes parties de l'adresse ?

ifdef::show_solutions[]

* `https://`: Le protocole utilisé. HTTP (Hypertext transfer protocol) est la façon dont les pages Internet et autres données sont transmises sur le World Wide Web. Le `s' à la fin indique que la connexion au site est cryptée.

* `openstreetmap.org`: Le domaine principal du projet OpenStreetMap. L'extension (="Top-Level-Domain") `.org` a été choisie pour souligner qu'il s'agit d'un projet de volontaires et non d'une entreprise commerciale comme beaucoup de `.com`. `osm.org` est un autre domaine du projet qui redirige vers les pages `openstreetmap.org' appropriées. Pour vous éviter de taper à la machine.

* `www.`: Eine Sub-Domain, die anzeigt, dass es sich um eine Website im World Wide Web (WWW) handelt. Etwas redundant, da das durch das HTTP-Protokoll und die global erreichbare Domain bereits impliziert ist.

* `#map=8/46.825/8.224`: La section de carte. Et il y en a une:

  * `8`: Le niveau de zoom. Plus ce nombre est élevé, plus la vue est agrandie.

  * `46.825`: Latitude en coordonnées WGS-84 comme nombre décimal (degrés avec décimales)

  * `8.224`: Longitude en coordonnées WGS-84 comme nombre décimal (degrés avec décimales)

.Dynamisation
Dans les leçons de géographie, il est souvent courant de spécifier les coordonnées angulaires en degrés, minutes et secondes. Profite de cette occasion pour pratiquer la conversion entre la fraction décimale et le système degré-minute-seconde. Par exemple, les informations de coordonnées du registre d'un atlas peuvent être traduites en URL OpenStreetMap.

endif::show_solutions[]

=== Tâche pour les SuS avancés / classes supérieures

Fais un zoom arrière jusqu'à ce que tu puisses voir des continents entiers ou même la terre entière. Puis déplace la carte vers le nord ou le sud sans zoomer. Pourquoi cela change-t-il l'échelle?

include::../../../snippets/quellenangabe.adoc[]
