= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Schüler und Interessierte

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Wissen im Bereich OpenStreetMap und Kartografie zu vermitteln, so dass Schüler 
und Interessierte danach in der Lage sind, auf Anweisung der Lehrperson/des Instruktors die Umgebung selbstständig 
zu kartografieren.

.Zielgruppe
Schüler und Interessierte

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit.

.Aufbau
Folgende Themen werden behandelt:

* Was ist OpenStreetMap (OSM)?
* Was wird kartiert? was nicht?
* Was könnte bei diesem Event alles kartiert werden?
* Vorbereitung
* Zurück am Laptop: Wie editiert man OSM?

== Einleitung

=== Was ist OpenStreetMap (OSM)?

OpenStreetMap (kurz OSM) ist ein Online-Geodatensystem, welches Geodaten enthält, die vom Benutzer gesammelt und 
verwaltet werden. Die Daten können frei und ohne Einschränkungen verwaltet werden und gehören der Community, man benötigt nur einen OSM-Account. 
Im Gegensatz dazu gehören die Daten von Bing Maps, Google Maps, CityMaps oder map.geo.admin.ch Unternehmen oder Regierungen, können vom Benutzer 
rechtlich gesehen also nicht einfach weiterverwendet werden. 

OpenStreetMap kann auf ganz verschiedene Art und Weise genutzt werden und die Benutzer können sehr unterschiedliche Ziele haben.
Um nur ein paar Beispiele zu nennen, liste ich im Folgenden ein paar Einsatzmöglichkeiten von OpenStreetMap auf:

* Privater Gebrauch zur Sammlung von Informationen bezüglich eines Ortes
* Navigationssysteme
* Statistiken und Analysen
* Infrastrukturplanung

Wenn du mehr über OpenStreetMap erfahren möchtest, dann schaue doch unter folgendem Link nach:
https://gitlab.com/openschoolmaps/openschoolmaps.gitlab.io/blob/master/lehrmittel/osm-org_als_kartenviewer/arbeitsblaetter_fuer_sus/01_webseite_osm-org_kennenlernen.adoc

=== Was wird kartiert? was nicht?

Unter Kartieren versteht man die Erfassung von raumbezogenen Daten, also Geodaten. Bevor man diese Daten jedoch in OpenStreetMap integrieren kann, 
muss man sie zuerst sammeln. Dazu hat man verschiedene Möglichkeiten. Eine Möglichkeit besteht im Recherchieren der Daten. Man durchsucht verschiedene 
Dokumente und/oder Webseiten und sammelt so Daten, die in OpenStreetMap noch fehlen oder nicht mehr aktuell sind. Eine andere Möglichkeit besteht in 
Umfragen von Menschen die Auskunft über noch fehlende Daten geben können. Die letzte Möglichkeit, beispielweise zum Erfassen von Häusern und Strassen 
ist, dass man loszieht und sich Notizen macht. Diese Notizen kann man dann zu einem späteren Zeitpunkt in OpenStreetMap übernehmen.

Das wichtigste beim kartieren ist, dass die Daten persistent, transparent und überprüfbar sind, so dass gewährleistet werden kann, 
dass sie auch stimmen. Unten siehst du zwei verschiedene Listen mit Beispielen von geeigneten und ungeeigneten OpenStreetMap-Daten:

Beispiele für geeignete Daten:

* Strassen
* Häuser
* Hausnummern
* Läden und Restaurants
* Öffnungszeiten
* Zugangsbeschränkungen

Beispiele für ungeeignete Daten:

* Persönliche Meinung
* Persönliche Daten
* Flugrouten
* Reviews zu Restaurants

=== Was könnte bei diesem Event alles kartiert werden?

Wie du oben schon gelesen hast, sind Strassen, Häuser, Hausnummern, Läden und Restaurants (inkl. Öffnungszeiten) geeignete Objekte/Daten zum Kartografieren. 
Bei diesem Event geht es also darum, dass du dich mit einem/einer Freund/in zusammenschliesst und in zweier Gruppen die Umgebung kartografiert. 

Doch wie kartografiert man richtig beziehungsweise auf was ist zu achten?

Strassen:

* Strassennamen
* Verlauf (gerade, kurvig, etc.)
* Richtung
* Fussgängerstreifen

Häuser und Hausnummern:

* Hausform
* Grösse der Fläche
* Adresse
* Evtl. hat ein Haus mehrere Nummern

Läden und Restaurants:

* Name des Ladens/Restaurants
* Öffnungszeiten
* Telefonnummer
* Adresse
* Website

== Vorbereitung

Bevor ihr in Zweiergruppen aufbricht um eure Umgebung zu erkunden und Daten zu sammeln, wäre es noch sinnvoll zu wissen, 
was ihr alles für einen reibungslosen Ablauf benötigt. Da ihr euch kaum die ganzen Eigenschaften der Strassen, Häuser, Hausnummern, Läden und Restaurants 
merken könnt, braucht ihr geeignete Hilfsmittel. Was gehen würde wären natürlich Stift und Papier, auf dem Papier sollte dann aber am besten schon 
ein Ausschnitt der Umgebung vorhanden sein (alles aufzeichnen wäre doch zu aufwendig). Noch einfacher als mit Stift und Papier zu arbeiten ist jedoch 
das Smartphone zu benutzen. Es reicht wenn ihr als Gruppe ein Smartphone benutzt.

Das nächste Kapitel kannst du dann zu einem späteren Zeitpunkt bearbeiten sobald du die Umgebung erkundet und alle Daten gesammelt hast. 
Viel Spass beim kartografieren!

== Zurück am Laptop: Wie editiert man OSM?

Nun da du zurück bist, können wir die Daten auf OpenStreetMap laden. Bevor wir anfangen können auf OpenStreetMap Daten zu bearbeiten oder hinzuzufügen, 
brauchst du noch einen OSM-Account. Doch gehen wir zunächst einmal zur Webseite unter: https://www.openstreetmap.org/.

Oben rechts siehst du nun einen "Registrieren"-Button. Klicke drauf, nun musst du deine Email eingeben und ein Passwort setzen. Per Email musst du dann 
deine Angaben bestätigen indem du auf einen Link klickst und danach ist dein Konto auch schon eingerichtet. Jetzt können wir beginnen, also 
legen wir doch mit dem eigentlichen Kartografieren los!


