= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Schüler und Interessierte

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Wissen im Bereich OpenStreetMap und Kartografie zu vermitteln, so dass Schüler 
und Interessierte danach in der Lage sind, auf Anweisung der Lehrperson/des Instruktors die Umgebung selbstständig 
zu kartografieren.

.Zielgruppe
Schüler und Interessierte

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit, allermindestens jedoch 2 Stunden.

.Aufbau
Folgende Themen werden behandelt:

* Was ist OpenStreetMap (OSM)?
* Was wird kartiert? was nicht?
* Was könnte bei diesem Event alles kartiert werden?
* Vorbereitung
* Wie editiert man OSM?

== Einleitung

=== Was ist OpenStreetMap (OSM)?

OpenStreetMap (kurz OSM) ist ein internationales Projekt ähnlich wie Wikipedia, 
bei dem Freiwillige Geodaten sammeln, die von unzählige (Web-)Applikationen 
verwendet werden.
Die OSM-Daten können gehören der Community und können - im Gegensatz beispielweise 
zu Google Maps oder map.geo.admin.ch - weiterverwendet werden im Rahmen der einer 
freien Lizenz. 

OpenStreetMap kann auf ganz verschiedene Art und Weise genutzt werden und die 
Benutzer können sehr unterschiedliche Ziele haben.
Im Folgenden listen wir ein paar Einsatzmöglichkeiten von OpenStreetMap auf:

* Zur Navigation mit dem Smartphone wie z.B. die Maps.Me-App
* Als Hintergrundkarte oder Lagekarte eingebetted in Webseiten
* Als Lage- und Wanderkarte
* Als Interaktive Webkarten aller Art
* Für Geoanalysen

Wenn du mehr über OpenStreetMap erfahren möchtest, dann schaue doch das 
Arbeitsblatt "Webseite OSM.org kennenlernen" an.

=== Was wird kartiert? was nicht?

Unter Kartieren versteht man die Erfassung von raumbezogenen Daten, also Geodaten. 
Bevor man diese Daten jedoch in OpenStreetMap integrieren kann, muss man sie zuerst sammeln. 
Dazu hat man verschiedene Möglichkeiten. 
Eine Möglichkeit besteht im Recherchieren der Daten. 
Man durchsucht verschiedene Dokumente und/oder Webseiten und sammelt so Daten, 
die in OpenStreetMap noch fehlen oder nicht mehr aktuell sind. 
Eine andere Möglichkeit besteht in Umfragen von Menschen die Auskunft über noch 
fehlende Daten geben können. 
Die letzte Möglichkeit, beispielweise zum Erfassen von Häusern und Strassen ist, 
dass man loszieht und sich Notizen macht. 
Diese Notizen kann man dann zu einem späteren Zeitpunkt in OpenStreetMap übernehmen.

Das Wichtigste beim Kartieren ist, dass überprüfbar ist, was man kartiert, so 
dass die Angaben nachgeprüft werden kann. 
Unten siehst du Beispiele von geeigneten und ungeeigneten Objekte:

Beispiele für geeignete Objekte:

* Strasse
* Haus
* Hausnummer
* Läden und Restaurants
* Öffnungszeit
* Zugangsbeschränkung

Beispiele für ungeeignete Objekte:

* Persönliche Meinung
* Persönliche Daten
* Flugrouten
* Bewertungen zu Restaurants

=== Was könnte bei diesem Event alles kartiert werden?

Wie du oben schon gelesen hast, sind Strassen, Häuser, Hausnummern, Läden und 
Restaurants (inkl. Öffnungszeiten) geeignete Objekte/Daten zum Kartografieren. 
Bei diesem Event geht es also darum, dass du dich mit einem/einer Freund/in 
zusammenschliesst und in Zweiergruppen die Umgebung kartografiert. 
Natürlich würde es viel zu lange dauern die ganze Umgebung zu kartografieren und 
seien wir ehrlich, dies wäre auch nicht sehr spannend. Deshalb suche dir einfach 
ein paar Orte in der Umgebung aus, welche dir gefallen. 
Beispiele hierfür wären dein Zuhause, falls es in der Nähe ist, ein Teil deines 
Schulweges, eine lokale Sehenswürdigkeit oder das Zuhause einer deiner Freunde. 
Es gibt genug Sachen die man kartografieren kann.

Doch wie kartografiert man richtig beziehungsweise auf was ist zu achten?

Strassen:

* Strassennamen
* Verlauf (gerade, kurvig, etc.)
* Richtung
* Fussgängerstreifen

Häuser und Hausnummern:

* Hausform
* Grösse der Fläche
* Adresse
* Evtl. hat ein Haus mehrere Nummern

Läden und Restaurants:

* Name des Ladens/Restaurants
* Öffnungszeiten
* Telefonnummer
* Adresse
* Website

== Vorbereitung

Bevor ihr in Zweiergruppen aufbricht um eure Umgebung zu erkunden und Daten zu 
sammeln, wäre es noch sinnvoll zu wissen, was ihr alles für einen reibungslosen 
Ablauf benötigt. 
Da ihr euch kaum die ganzen Eigenschaften der Strassen, Häuser, Hausnummern, 
Läden und Restaurants merken könnt, braucht ihr geeignete Hilfsmittel. 
Was gehen würde wären natürlich Stift und Papier, auf dem Papier sollte 
dann aber am besten schon ein Ausschnitt der Umgebung vorhanden sein (alles 
aufzeichnen wäre doch zu aufwendig). 
Es ist auch möglich, ein Smartphone mit GPS zu nutzen. Das verwenden wir aber 
hier noch nicht, denn das braucht mehr Vor- und Nachbereitung als Stift und Papier. 

== Fieldpapers

Field Papers ist eine Webapplikation, mit dem man eine Karte eines Gebietes drucken, darauf zeichnen und Notizen machen kann. Die Notizen werden dann wieder eingescannt und in die Webapplikation hochgeladen. Damit kann man die Notizen im OpenStreetMap-Editor anzeigen und die Objekte dort eintragen. 

Auf Webseite findest du weitere Erklärungen: http://fieldpapers.org/

Das nächste Kapitel erläutert, wie man die erfassten Daten am Laptop/PC editiert, 
sobald du Daten gesammelt hast. 
Viel Spass beim Kartografieren!

== Wie editiert man OSM?

Nun da du zurück bist, können wir die Daten auf OpenStreetMap laden. 
Bevor wir anfangen können auf OpenStreetMap Daten zu bearbeiten oder hinzuzufügen, 
brauchst du einen OSM-Account. 
Dazu gehen wir zur Webseite unter: https://www.openstreetmap.org/.

Oben rechts siehst du nun einen "Registrieren"-Button. 
Klicke drauf, nun musst du deine Email eingeben und einen Benutzernamen und ein Passwort setzen. 
Per Email musst du dann deine Angaben bestätigen, indem du auf einen Link klickst
und danach ist dein Konto auch schon eingerichtet. 

Jetzt kannst du mit dem eigentlichen Kartografieren beginnen, also los!

//TODO
