= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Interessierte, für Lehrpersonen und beispielsweise Maturanden

== Übersicht

.Ziel
Eine Lehrperson bzw. ein Instruktor soll ein Outdoor Mapping Event von einem Tag planen können für eine Gruppe 
von Schülern bzw. Interessierten. Die Anleitung soll nicht nur für Schüler gelten sondern auch für andere. 
Es gibt einen Raum mit Laptop-Anschlussmöglichkeiten (Strom und Internet). Die Schüler/Interessierten haben 
mindestens zu zweit ein Smartphone. Ein Drucker für die Lehrperson/Instruktor 

.Zielgruppe
Lehrpersonen und Instruktoren, evtl. Interessierte und Maturanden

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit.

.Aufbau
Folgende Themen werden behandelt:

* Was ist OpenStreetMap (OSM)?
* Was wird kartiert? was nicht?
* Was könnte bei diesem Event alles kartiert werden?
* Wie kartieren wir draussen?
* Vorbereitung
* Zurück am Laptop: Wie editiert man OSM?

== Einleitung

=== Was ist OpenStreetMap (OSM)?


