= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Interessierte, für Lehrpersonen und beispielsweise Maturanden

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Wissen im Bereich OpenStreetMap und Kartografie zu vermitteln, so dass Schüler 
und Interessierte danach in der Lage sind, auf Anweisung der Lehrperson/des Instruktors die Umgebung selbstständig 
zu kartografieren.

.Zielgruppe
Schüler und Interessierte

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit.

.Aufbau
Folgende Themen werden behandelt:

* Was ist OpenStreetMap (OSM)?
* Was wird kartiert? was nicht?
* Was könnte bei diesem Event alles kartiert werden?
* Wie kartieren wir draussen?
* Vorbereitung
* Zurück am Laptop: Wie editiert man OSM?

== Einleitung

=== Was ist OpenStreetMap (OSM)?


