= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Schüler und Interessierte

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Wissen im Bereich OpenStreetMap und Kartografie zu vermitteln, so dass Schüler 
und Interessierte danach in der Lage sind, auf Anweisung der Lehrperson/des Instruktors die Umgebung selbstständig 
zu kartografieren.

.Zielgruppe
Schüler und Interessierte

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit.

.Aufbau
Folgende Themen werden behandelt:

* Was ist OpenStreetMap (OSM)?
* Was wird kartiert? was nicht?
* Was könnte bei diesem Event alles kartiert werden?
* Wie kartieren wir draussen?
* Vorbereitung
* Zurück am Laptop: Wie editiert man OSM?

== Einleitung

=== Was ist OpenStreetMap (OSM)?

OpenStreetMap (kurz OSM) ist ein Online-Geodatensystem, welches Geodaten enthält, die vom Benutzer gesammelt und 
verwaltet werden. Die Daten können frei und ohne Einschränkung verwaltet werden und gehören der Community, man benötigt nur einen OSM-Account. 
Im Gegensatz dazu gehören die Daten von Bing Maps, Google Maps, CityMaps oder map.geo.admin.ch Unternehmen oder Regierungen, können vom Benutzer 
rechtlich gesehen nicht einfach weiterverwendet werden.

