= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Lehrpersonen und Instruktoren

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Lehrpersonen und Instruktoren einen 
Überblick zu verschaffen wie man erfolgreich ein Outdoor Mapping Event für 
Interessierte bzw. Schülerinnen und Schüler durchführt.

.Zielgruppe
Lehrpersonen und Instruktoren

.Zeitplanung
Dies ist kein Arbeitsblatt sondern eine Einleitung mit einer Sammlung von 
Hinweisen.

.Aufbau
Folgende Themen werden behandelt:

* Um was geht's (Einleitung)?
* Checkliste
* Vorbereitungen
* Den Event auswerten und Abschluss des Events 

== Einleitung

Technologie ist immer weniger aus dem Alltag der Menschen zu denken, dazu gehören 
auch Online-Kartendienste und GPS-Navigationssysteme. 
Viele kennen fast nur Google Maps. 
Dabei gibt es viele Alternativen dazu und eine ganz besondere ist OpenStreetMap. 
Der Vorteil von OpenStreetMap ist, dass die Daten den Nutzern (der Community) 
gehören und nicht einem Unternehmuen oder einer Behörde. 
Dies setzt aber auch voraus, dass die Daten durch die Nutzer ergänzt und aktuell 
gehalten werden. 
Und Kartografieren ist weder langweilig noch schwierig, darum sollte es jeder 
können. 
Eine Möglichkeit, das Kartografieren bekannter zu machen, ist es in den 
Unterricht einzubinden, beispielsweise im Geografie- oder Geschichtsunterricht. 
Ein Outdoor Mapping Event soll einen Einblick geben.

Die unten abgebildete Checkliste beinhaltet eine kurze Auflistung der Themen, 
die wichtig sind um einen erfolgreichen Event lancieren zu können. 
Auf die Themen wird Abschnitt für Abschnitt näher eingegangen.

== Checkliste zur Durchführung eines Outdoor Mapping Events

* Studium der Unterlagen
* Durchführung eines Testlaufs
* Integrieren der Daten in OpenStreetMap (u.a. Festlegen des Changeset-Kommentars)
* Vorbereitungen (u.a. Gruppen bilden)
* Gebiet einteilen und Kartenausschnitte drucken (Teil der Vorbereitung)
* Einführung der Thematik für die Teilnehmenden (Teil der Vorbereitung)
* Event auswerten und Abschluss des Events

== Studium der Unterlagen

Bevor Sie ein erfolgreiches Outdoor Mapping Event durchführen können, müssen Sie 
sich mit der Thematik befassen. 
Es wäre gut, wenn Sie einige Wochen im Voraus die Unterrichtsmaterialien von 
https://openschoolmaps.ch/[OpenSchoolMaps] zur Hand nehmen und diese studieren. 
Die Unterlagen beinhalten sowohl Theorie wie auch Aufgaben zum Lösen. 
Seien Sie auf mögliche Fragen der Schülerinnen und Schüler vorbereitet und 
machen Sie sich Notizen. 
Wenn etwas nicht ganz klar ist, kann man sich im Web informieren. 
Dies ist ein guter Einstiegspunkt https://osm.ch/hilfe.html[OSM.ch].
Bei der "Swiss OpenStreetMap Association" gibt es auch einen direkten https://sosm.ch/[Kontakt].
Das Studieren der Unterlagen sollte jedoch gut im Selbststudium machbar sein.

== Durchführung eines Testlaufs

Zu einer gewissenhaften Vorbereitung gehört nicht nur das Studieren der 
Unterlagen, sondern auch das Durchführen eines Testlaufs. 
Gehen Sie auf einen Spaziergang und wenden Sie Ihr neu erworbenes Wissen auf 
Ihre Umgebung an. 
Erkunden Sie die Umgebung aus Sicht eines Kartografierers. 
Nehmen Sie Stift und Papier mit auf den Spaziergang. 
Nutzen Sie dafür die Kartenwerkzeuge uMap oder Field Papers, wie unten 
beschrieben. 

Es gäbe auch die Möglichkeit das Smartphone zu nutzen, beispielsweise mit dem 
App "OSMTracker for Android".
Doch ist das mit mehr Organisations- und Erklärungsaufwand verbunden und dem 
stetigen technischen Wandel unterworfen.

Stoppen Sie die Zeit und schauen Sie nach wie lange Sie für ihre 
Umgebungserkundung benötigen und wie viel Informationen Sie in dieser Zeit 
sammeln können, dann fällt es Ihnen leichter abzuschätzen, wie viel Zeit Sie für 
die Schülerinnen und Schüler und Teilnehmenden planen.

== Integrieren der Daten in OpenStreetMap

Nachdem Sie Ihre Daten gesammelt haben, gehen Sie auf https://www.osm.org[OSM.org]
und tragen Sie Ihre Daten ein. 

Falls Sie noch kein Konto bei OpenStreetMap (OSM) haben, ist jetzt der Zeitpunkt 
dafür, eines anzulegen. 
Beachten Sie auch das Arbeitsblatt "OpenStreetMap bearbeiten" auf 
https://openschoolmaps.ch/[OpenSchoolMaps] für weitere Erklärungen.

Auch hier könnte es sich als Vorteil erweisen, wenn Sie schauen, 
wie viel Zeit Sie benötigen. 
Rechnen Sie zu ihrer gemessenen Zeit noch ein wenig dazu, denn die 
Schülerinnen und Schüler sind wahrscheinlich nicht gleich schnell wie Sie und 
die Unterschiede können beträchtlich sein. 

Vor dem Speichern der editierten Daten ist bei OpenStreetMap immer ein 
sogenannter "Changeset-Kommentar" nötig.
Damit dieser Event ausgewertet werden kann, ist es wichtig, dass alle denselben
Changeset-Kommentar verwenden.
Legen Sie fest, welchen Changeset-Kommentar alle verwenden sollen.
Ein Beispiel für ein Changeset-Kommentar ist "Outdoor Event der HSR Rapperswil 
vom 11.6.2019".

CAUTION: Zeigen Sie Ihre Arbeit den Teilnehmenden als Einführung ins Thema. 
So erhalten Sie schon einen ersten Eindruck.

== Vorbereitung

Die Teilnehmenden sollten zur Durchführung des Events Gruppen bilden, z.B. 
Zweiergruppen. 
Dies macht es für die Teilnehmenden spannender und für die Lehrperson bzw. den 
Instruktor einfacher zu organisieren. 
Zudem sollte ein Raum zur Verfügung stehen mit genügend Computern mit Zugang zum 
Internet, um auf OpenStreetMap.org die gesammelten Daten zu integrieren. 
Weiter sind Stifte und gedruckte Kartenausschnitte nötig. 
Sie dazu nachfolgend weitere Erläuterungen.
Nicht zwingend - aber natürlich wünschenswert - ist schönes Wetter, da es um 
eine Outdoor-Aktivität geht. 

CAUTION: Achten Sie darauf, dass Sie genug Lektionen einplanen. 
Kartografieren kann länger dauern als man denkt, deshalb planen Sie grosszügig!

== Gebiet einteilen und Kartenausschnitte drucken

Das für den Event geplante Gebiet muss eingegrenzt werden, damit die 
Teilnehmenden nicht zu grosse Distanzen überwinden müssen. 
Zudem ist es sinnvoll, das Gebiet in kleinere Gebiete 
(sogenannte "Perimeter") einzuteilen und den Gruppen zuzuweisen.
Damit wird dieselbe Gegend nicht zweimal kartographiert.

Für die Gebietseinteilung eignen sich vor allem zwei Webapplikationen: 
uMap und Field Papers:

* uMap ist ein Karteneditor, mit dem man beliebige Gebiete einzeichnen 
kann. Auf https://openschoolmaps.ch/[OpenSchoolMaps] gibt   
es ein eigenes Unterrichtsmaterial "Mit uMap einen Lageplan erstellen" dazu. 
* "Field Papers" ist eine spezialisierte Webapplikation, die es ermöglicht, 
Kartenausschnitte zu erstellen und die im Feld gemachten Notizen wieder 
hochzuladen, damit man sie beim Editieren direkt sieht.

Wenn Sie sich für uMap entscheiden, dann können Sie folgende Erläuterungen
überspringen und müssen nur noch dafür sorgen, dass für alle Gruppen genügend 
Karten ausgedruckt sind.

*"Field Papers"* ist eine Webapplikation mit der man aus OpenStreetMap eine Karte 
erstellen, diese ausdrucken und mit eigenen Notizen versehen kann. 
Wenn die Notizen auf der Karte erfasst sind, können sie abfotografiert (oder 
eingescannt) und bei Field Papers wieder hochgeladen werden. 
Nachdem die Karte hochgeladen ist, kann man mit einem Klick direkt den 
OpenStreetMap-Editor iD aufrufen und sieht die Notizen als Basiskarte. 
Hier ein http://www.openstreetmap.org/edit#background=custom:http://tiles.fieldpapers.org/snapshots/5mq7v8ph/{z}/{x}/{y}.png&map=18/47.22425/8.81875[Beispiel] 
bei dem man Link sieht, dass der der Editor mit Parametern aufgerufen wird. 
Nun kann man im OpenStreetMap iD-Editor die Daten erfassen und sieht dabei die 
abfotografierten Notizen im Hintergrund.

Für Field Papers benötigt man einen Computer, einen Drucker mit A4-Papier und 
eine Digitalkamera (z.B. Kamera im Smartphone).

Nachfolgend ist der Ablauf mit Field Papers zusammengefasst:

1. Rufen Sie http://fieldpapers.org/[Field Papers] auf 
1. Registrieren Sie sich bei Field Papers wenn nötig. 
1. Geben Sie der Karte einen Namen und navigieren Sie zum Gebiet, das Sie 
kartieren (lassen) wollen.
1. Drucken Sie die Karten ("Atlas") aus.
1. Gehen Sie nach draussen und notieren Sie, was Sie siehen.
1. Zurück am Computer, schauen Sie sich entweder einfach die Papier-Notizen an 
als Hilfsmittel;
1. oder machen Sie ein Foto der Papier-Notizen (auch einscannen geht) und laden 
Sie das Foto oder den Scan hoch auf Field Papers.
1. Starten den iD-Editor und zwar direkt mit dem Weblink auf Field Papers.
1. Erfasse die Daten mit dem OpenStreetMap-Editor. 

Auf der http://fieldpapers.org/about[Webseite] von Field Papers und auf dem 
https://wiki.openstreetmap.org/wiki/Field_Papers[OSM Wiki] gibt es weitere 
Informationen.

== Einführung der Thematik für die Teilnehmenden

Bevor Sie die Teilnehmenden in Gruppen einteilen und losschicken, um die Umgebung 
zu erkunden, sollten Sie sie ans Thema heran führen. 
Dies deshalb, da der Wissensstand innerhalb der Klasse/Gruppe im Bereich der 
Informatik doch sehr gross sein kann und nicht alle wissen, was OpenStreetMap 
ist und was der Sinn und Zweck dahinter sein soll. 
Bereiten Sie am Besten eine kurze Präsentation vor und tragen Sie alles vor, was 
Sie in den Unterlagen gelernt haben und wissen. 
Nehmen Sie sich Zeit, um offene Fragen zu klären und gehen Sie sicher, dass die 
Teilnehmenden auch alles verstanden haben.

== Event auswerten und Abschluss des Events 

Am Schluss des Events sollen die Teilnehmenden Ihre Ergebnisse auswerten und vor 
allen präsentieren. 
Das Auswerten kann entweder jede/r für sich alleine oder pro Gruppe geschehen. 
Zum Auswerten gehören Vorher-Nachher-Vergleiche der Kartenausschnitte, 
statistische Auswertungen und die persönliche Reflexion.

Nach dem Auswerten des Events und den Präsentationen der Ergebnisse wäre es auch 
sinnvoll, ein Fazit zu ziehen. 
Was war gut? Was war nicht so gut? Was kann man nächstes Mal besser machen? 
Was hat die Klasse gelernt? 
Diese Feststellungen könnten in einem Bericht festgehalten werden.

Die Präsentationen können natürlich, falls vom Instruktor gewünscht, benotet 
werden. 
Man könnte anstelle einer Präsentation auch eine Art Dokumentation der Arbeit 
veranlassen und ev. benoten. 
Eine Rückmeldung des Events an den Initianten von OpenSchoolMaps wäre auch 
toll, damit auch sie sich verbessern können und in Zukunft weitere Lerninhalte 
veröffentlichen können: siehe https://openschoolmaps.ch/[OpenSchoolMaps] > 
"Weitere Unterrichtsideen". 