= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Lehrpersonen und Instruktoren

== Übersicht

.Ziel
Dies ist kein Arbeitsblatt sondern eine Sammlung von Hinweisen und Tipps 
für Lehrpersonen und Instruktoren zur Organisation eines erfolgreichen 
Outdoor Mapping Events (manchmal auch "Mapping Party" genannt) mit Schülerinnen 
und Schülern und Interessierten (hier "Teilnehmende" genannt).

.Zielgruppe
Lehrpersonen und Instruktoren

== Einleitung

Technologie ist kaum aus unserem Alltag weg zu denken. 
Dazu gehören auch Online-Kartendienste und GPS-Navigationssysteme. 
Viele kommt dabei nur Google Maps in den Sinn. 
Dabei gibt es viele Alternativen - und eine ganz besondere ist OpenStreetMap (kurz OSM). 
Der Vorteil von OpenStreetMap ist, dass die Daten den Nutzern (der Community) 
gehören und nicht einem Unternehmen oder einer Behörde. 
Dies setzt aber auch voraus, dass die Daten durch die Nutzer ergänzt und aktuell 
gehalten werden. 
Und Kartografieren ist weder langweilig noch schwierig, darum sollte es jeder 
können. 
Eine Möglichkeit, das Kartografieren bekannter zu machen, ist es in den 
Unterricht einzubinden, beispielsweise im Geografie- oder Geschichtsunterricht. 
Ein Outdoor Mapping Event soll einen Einblick geben.

Die unten abgebildete Checkliste beinhaltet eine kurze Auflistung der Themen, 
die wichtig sind um einen erfolgreichen Event lancieren zu können. 
Zudem wird eine Übersicht über die Zeitplanung des Events gegeben.

Auf die Themen wird Abschnitt für Abschnitt näher eingegangen.

== Checkliste und Zeitplanung

Nachfolgend eine Checkliste für Lehrpersonen und Instruktoren zur Vorbereitung 
und Durchführung eines Outdoor Mapping Events:

1. Studium der Unterlagen
1. Durchführung eines Testlaufs
1. Integrieren der Daten in OpenStreetMap
1. Vorbereitungen (u.a. Festlegen Gruppen, Changeset-Kommentar, etc.)
1. Gebiet einteilen und Kartenausschnitte drucken (Teil der Vorbereitung)
1. Einführung der Thematik für die Teilnehmenden (Teil der Vorbereitung)
1. Nach Durchführung des Events, den Event auswerten und abschliessen

Nachfolgend eine Tabelle als Übersicht über die Zeitplanung des Events. 
Es gibt verschiedene Möglichkeiten, je nachdem ob Sie einen Outdoor Mapping 
Event planen im Rahmen ( A ) des regulären Unterrichts, ( B ) einer Projektwoche an 
der Schule, oder ( C ) einer Projektwoche ausserhalb der Schule, dann sind das 
hier unsere geschätzten Zeitangaben:

[cols="1,1,1,1", options="header"] 
.Zeitplanung Übersicht. 
|===
|Phase
|A. Regulärer Unterricht
|B. Projektwoche an Schule
|C. Projektwoche ausserhalb Schule

|Einführung
|2 - 4 Lektionen
|4 Lektionen
|4 Lektionen

|Datenerhebung (draussen)
|3 Lektionen
|2 Tage
|2 Tage

|Datenerfassung (am Computer)
|3 Lektionen
|1 Tag
|1 Tag

|Bericht schreiben
|-
|-
|0.5 Tage

|Abschluss
|2 Lektionen
|0.5 Tage
|0.5 Tage

|===

== Studium der Unterlagen

Bevor Sie einen erfolgreichen Outdoor Mapping Event durchführen können, müssen 
Sie sich mit der Thematik von OpenStreetMap befassen. 
Es wäre gut, wenn Sie einige Wochen im Voraus die Unterrichtsmaterialien von 
https://openschoolmaps.ch/[OpenSchoolMaps] zur Hand nehmen und diese studieren. 
Die Unterlagen beinhalten sowohl Theorie wie auch Aufgaben zum Lösen. 
Seien Sie auf mögliche Fragen der Teilnehmenden vorbereitet und 
machen Sie sich Notizen. 
Wenn etwas nicht ganz klar ist, kann man sich im Web informieren. 
Dies ist ein guter Einstiegspunkt https://osm.ch/hilfe.html[OSM.ch].
Das Studieren der Unterlagen sollte jedoch gut im Selbststudium machbar sein.

[NOTE]
====
Bei der "Swiss OpenStreetMap Association" (SOSM) gibt es die Möglichkeit, Fragen zu 
stellen, falls Sie nicht mehr weiterkommen: https://sosm.ch/de/kontakt/[Kontakt].
====

== Durchführung eines Testlaufs

Zu einer gewissenhaften Vorbereitung gehört nicht nur das Studieren der 
Unterlagen, sondern auch das Durchführen eines Testlaufs. 
Gehen Sie auf einen Spaziergang und wenden Sie Ihr neu erworbenes Wissen auf 
Ihre Umgebung an. 
Erkunden Sie die Umgebung aus Sicht eines Kartografierers. 
Nehmen Sie Stift und Papier mit auf den Spaziergang. 
Nutzen Sie dafür die Kartenwerkzeuge uMap oder Field Papers, wie unten 
beschrieben. 

Es gäbe auch die Möglichkeit das Smartphone zu nutzen, beispielsweise mit der 
App "OSMTracker for Android".
Doch ist das mit mehr Organisations- und Erklärungsaufwand verbunden und dem 
stetigen technischen Wandel unterworfen.

Stoppen Sie die Zeit und schauen Sie nach wie lange Sie für ihre 
Umgebungserkundung benötigen und wie viel Informationen Sie in dieser Zeit 
sammeln können, dann fällt es Ihnen leichter abzuschätzen, wie viel Zeit Sie für 
die Teilnehmenden planen.

CAUTION: Achten Sie darauf, dass Sie genug Lektionen einplanen. 
Kartografieren kann länger dauern als man denkt, deshalb planen Sie grosszügig!

== Integrieren der Daten in OpenStreetMap

Nachdem Sie Ihre Daten gesammelt haben, gehen Sie auf https://www.osm.org[OSM.org]
und tragen Sie Ihre Daten ein. 

Falls Sie noch kein Konto bei OpenStreetMap (OSM) haben, ist jetzt der Zeitpunkt 
dafür, eines anzulegen. 
Beachten Sie auf https://openschoolmaps.ch/[OpenSchoolMaps] unter 
"Unterrichtsmaterialien" auch das Arbeitsblatt "OpenStreetMap bearbeiten" für 
weitere Erklärungen, sowie das "OpenStreetMap Tagging Cheatsheet".

Auch hier könnte es sich als Vorteil erweisen, wenn Sie schauen, 
wie viel Zeit Sie benötigen. 
Rechnen Sie zu ihrer gemessenen Zeit noch ein wenig dazu, denn die Teilnehmenden 
sind wahrscheinlich nicht gleich schnell wie Sie und die Unterschiede können 
beträchtlich sein. 

Vor dem Speichern der editierten Daten ist bei OpenStreetMap immer ein 
sogenannter "Changeset-Kommentar" nötig.
Ein Beispiel für ein Changeset-Kommentar ist "Outdoor Event Rappi 2019-06-11".
Im folgenden Kapitel "Vorbereitungen" kommen wir nochmals auf diesen Kommentar 
zurück.

[NOTE]
=====
Zeigen Sie Ihre Arbeit den Teilnehmenden als Einführung ins Thema. 
So erhalten Sie schon einen ersten Eindruck.
=====

== Vorbereitungen

*Termin festlegen*: Für den Durchführungs-Termin ist nicht zwingend - aber 
natürlich wünschenswert - wenn schönes Wetter angekündigt ist, da es um eine 
Outdoor-Aktivität geht. 
Evtl. könnte ein Ausweichtermin festgelegt werden.

*Gruppeneinteilung planen*: Die Teilnehmenden sollten zur Durchführung des 
Events Gruppen bilden, z.B. Zweiergruppen. 
Dies macht es für die Teilnehmenden spannender und für die Lehrperson bzw. den 
Instruktor einfacher zu organisieren. 
Jeder Gruppe soll ein Gebiet zugeteilt werden, wie nachfolgend noch erläutert wird.

*E-Mail-Adressen einrichten*: Um Services wie OpenStreetMap nutzen zu können, 
benötigt man eine E-Mail-Adresse.
Und für diese Nutzung muss man gemäss Internet-Recht älter als 13 Jahre sein. 
Bei 13- bis 16-Jährigen Teilnehmenden kann ein Elternteil oder eine von den 
Eltern autorisierte Person (eine Lehrperson, ein Schuldadministrator oder ein 
Instruktor) Benutzerkonten verwalten (https://wiki.osmfoundation.org/wiki/Terms_of_Use#II._Privacy[Quelle]). 

[NOTE]
====
Auf folgender Webseite finden Sie einige Tipps, wie Sie für die Gruppe 
E-Mail-Adressen einrichten können unter Berücksichtigung der Privatsphäre 
und des Datenschutzes: https://giswiki.hsr.ch/Micro_Mapping_Party_Rapperswil#E-Mail-Adressen_f.C3.BCr_Gruppe_oder_Klasse_einrichten[GISWiki HSR].
====

*Changeset-Kommentar festlegen*: Vor dem Speichern der editierten Daten ist bei 
OpenStreetMap immer ein sogenannter "Changeset-Kommentar" nötig.
Damit ein Event ausgewertet werden kann, ist es wichtig, dass alle denselben
Changeset-Kommentar verwenden.
Legen Sie fest, welchen Changeset-Kommentar alle verwenden sollen.
Er sollte nictht länger als 32 Zeichen lang sein. 
Ein Beispiel für ein Changeset-Kommentar ist _Outdoor Event Rappi 2019-06-11_.

*Event als Zusammenfassung ankündigen*: Auch OpenStreetMap kennt Regeln - 
ähnlich wie eine Allmend oder ein Schulplatz. 
Es ist beispielsweise wichtig, dass diejenigen, die editieren, kontaktiert 
werden können. 
Bei einem Event wie diesem spricht man von organisiertem Editieren und dazu gibt
es diese https://wiki.openstreetmap.org/wiki/DE:Organised_Editing_Guidelines["Organised Editing Guidelines"].
Wir haben diese Richtlinien für Sie auf's Wichtigste gekürzt.

Gemäss den Richtlinien werden Sie gebeten, folgende Angaben auszufüllen und an 
folgenden Kontakt zu mailen: https://sosm.ch/de/kontakt/[SOSM]. 

[NOTE]
====
*Zusammenfassung (Summary) des Outdoor Mapping Events:* 

Name des Events: ... _(z.B. Outdoor Event Rappi)_ +
Durchführungsdatum (date): ... _(z.B. 2019-06-11)_ +
Changeset-Kommentar: ... _(max. 32 Zeichen! z.B. Outdoor Event Rappi 2019-06-11)_ +
Instruktor (coordinator): ... _(z.B. Username Geonick)_ +
Teilnehmende (participants): ..., ... _(z.B. Usernamen wie: Geonick, Username2, ...)_ +
Ziele (goals): ... _(z.B. Die Umgebung von Rapperswil-Jona kartieren)_
====

Zur Infrastruktur und Verbrauchsmaterial:

* Es sollte ein Raum zur Verfügung stehen mit genügend Computern mit Zugang zum 
Internet, um auf OpenStreetMap.org die gesammelten Daten zu integrieren. 
* Im nachfolgenden Kapitel ist erklärt, wie gedruckte Kartenausschnitte erstellt 
werden können. 
* Evtl. Unterlagen für die Kartennotizen beschaffen.
* Genügend Schreib-Stifte 

Beachten Sie auch die Checkliste zuhanden der Teilnehmenden im zugehörigen 
Arbeitsblatt für Schülerinnen und Schüler sowie Interessierte.

== Gebiet einteilen und Kartenausschnitte drucken

Das für den Event geplante Gebiet muss eingegrenzt werden, damit die 
Teilnehmenden nicht zu grosse Distanzen überwinden müssen. 

Zudem ist es sinnvoll, das Gebiet in kleinere Gebiete 
(sogenannte "Perimeter") einzuteilen und den Gruppen zuzuweisen.
Damit wird dieselbe Gegend nicht zweimal kartographiert.

Für die Gebietseinteilung eignen sich vor allem zwei Webapplikationen: 
uMap und Field Papers:

* uMap ist ein Karteneditor, mit dem man beliebige Gebiete einzeichnen 
kann. Auf https://openschoolmaps.ch/[OpenSchoolMaps] gibt   
es ein eigenes Unterrichtsmaterial "Mit uMap einen Lageplan erstellen" dazu. 
* "Field Papers" ist eine spezialisierte Webapplikation, die es ermöglicht, 
Kartenausschnitte zu erstellen und die im Feld gemachten Notizen wieder 
hochzuladen, damit man sie beim Editieren direkt sieht.

Wenn Sie sich für uMap entscheiden, dann können Sie folgende Erläuterungen
überspringen und müssen nur noch dafür sorgen, dass für alle Gruppen genügend 
Karten ausgedruckt sind.

*"Field Papers"* ist eine Webapplikation mit der man aus OpenStreetMap eine Karte 
erstellen, diese ausdrucken und mit eigenen Notizen versehen kann. 
Wenn die Notizen auf der Karte erfasst sind, können sie abfotografiert (oder 
eingescannt) und bei Field Papers wieder hochgeladen werden. 
Nachdem die Karte hochgeladen ist, kann man mit einem Klick direkt den 
OpenStreetMap-Editor iD aufrufen und sieht die Notizen als Basiskarte. 
Hier ein http://www.openstreetmap.org/edit#background=custom:http://tiles.fieldpapers.org/snapshots/5mq7v8ph/{z}/{x}/{y}.png&map=18/47.22425/8.81875[Beispiel] 
bei dem man Link sieht, dass der der Editor mit Parametern aufgerufen wird. 
Nun kann man im OpenStreetMap iD-Editor die Daten erfassen und sieht dabei die 
abfotografierten Notizen im Hintergrund.

Für Field Papers benötigt man einen Computer, einen Drucker mit A4-Papier und 
eine Digitalkamera (z.B. Kamera im Smartphone).

Nachfolgend ist der Ablauf mit Field Papers zusammengefasst:

1. Rufen Sie http://fieldpapers.org/[Field Papers] auf 
1. Registrieren Sie sich bei Field Papers wenn nötig. 
1. Geben Sie der Karte einen Namen und navigieren Sie zum Gebiet, das Sie 
kartieren (lassen) wollen.
1. Drucken Sie die Karten ("Atlas") aus.
1. Gehen Sie nach draussen und notieren Sie, was Sie siehen.
1. Zurück am Computer, schauen Sie sich entweder einfach die Papier-Notizen an 
als Hilfsmittel;
1. oder machen Sie ein Foto der Papier-Notizen (auch einscannen geht) und laden 
Sie das Foto oder den Scan hoch auf Field Papers.
1. Starten den iD-Editor und zwar direkt mit dem Weblink auf Field Papers.
1. Erfasse die Daten mit dem OpenStreetMap-Editor. 

Auf der http://fieldpapers.org/about[Webseite] von Field Papers und auf dem 
https://wiki.openstreetmap.org/wiki/Field_Papers[OSM Wiki] gibt es weitere 
Informationen.

== Einführung der Thematik für die Teilnehmenden

Bevor Sie die Teilnehmenden in Gruppen einteilen und losschicken, um die Umgebung 
zu erkunden, sollten Sie sie ans Thema heran führen. 
Dies deshalb, da der Wissensstand innerhalb der Klasse/Gruppe im Bereich der 
Informatik doch sehr gross sein kann und nicht alle wissen, was OpenStreetMap 
ist und was der Sinn und Zweck dahinter sein soll. 
Bereiten Sie am Besten eine kurze Präsentation vor und tragen Sie alles vor, was 
Sie in den Unterlagen gelernt haben und wissen. 
Nehmen Sie sich Zeit, um offene Fragen zu klären und gehen Sie sicher, dass die 
Teilnehmenden auch alles verstanden haben.

== Event auswerten und abschliessen 

Am Schluss des Events sollen die Teilnehmenden Ihre Ergebnisse auswerten 
und vor allen präsentieren. 
Das Auswerten kann entweder jede/r für sich alleine oder pro Gruppe geschehen. 
Zum Auswerten gehören Vorher-Nachher-Vergleiche der Kartenausschnitte, 
statistische Auswertungen und die persönliche Reflexion.
Die Präsentationen können natürlich, falls vom Instruktor gewünscht, benotet 
werden. 
Man könnte anstelle einer Präsentation auch eine Art Dokumentation der Arbeit 
veranlassen und evtl. benoten. 

Nach dem Auswerten des Events und den Präsentationen der Ergebnisse wäre es auch 
sinnvoll, wenn Sie ein Fazit ziehen: Was war gut? Was war nicht so gut? Was 
kann man nächstes Mal besser machen? Was hat die Klasse gelernt? 
Diese Feststellungen könnten Sie in einem Bericht festhalten.

[NOTE]
====
Der Changeset-Kommentar, den Sie festgelegt haben und den die Teilnehmenden 
(hoffentlich) beim Editieren angegeben haben, kann genutzt werden,
um eine Analyse der geleisteten Arbeit zu machen. 
Dazu kann der Changeset-Kommentar in folgender Webapplikation angegeben werden, 
worauf man eine Statistik erhält (über die letzten 30 Tage): 
https://resultmaps.neis-one.org/osm-changesets?#8/46.856/8.405 . 
Bei "Search for a specific Text" können man z.B. probehalber "Schweiz" eingeben.
====

Eine Rückmeldung zum Event an die Initianten von OpenSchoolMaps wäre auch 
toll, damit auch sie sich verbessern können: siehe 
https://openschoolmaps.ch/[OpenSchoolMaps] > 
"Weitere Unterrichtsideen". 