= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Lehrpersonen und Instruktoren

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Lehrpersonen und Instruktoren einen Überblick zu verschaffen 
wie man erfolgreich ein Outdoor Mapping Event für die Schülerinnen und Schüler einer Klasse durchführt.

.Zielgruppe
Lehrpersonen und Instruktoren

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit.

.Aufbau
Folgende Themen werden behandelt:

* Einleitung
* Checkliste
* Vorbereitung
* Den Event auswerten und Abschluss des Events 

== Einleitung



== Checkliste



== Vorbereitung



== Den Event auswerten und Abschluss des Events 

Am Schluss des Events sollen die Schülerinnen und Schüler ihre Ergebnisse auswerten und der Klasse präsentieren. 
Das Auswerten kann entweder jeder für sich oder pro Zweiergruppe geschehen. Zum Auswerten gehören Vorher-Nachher-Vegleiche 
der Kartenausschnitte, statistische Auswertungen und die persönliche Reflexion. Nach dem Auswerten des Events und den Präsentationen 
der Ergebnisse wäre es auch noch sinnvoll, innerhalb der ganzen Klasse ein Fazit zu ziehen. Was war gut? Was war nicht so gut? Was kann 
man nächstes Mal besser machen? Was hat die Klasse gelernt? Diese Feststellungen sollten unbedingt in einem Bericht festgehalten werden.

Die Präsentationen können natürlich, falls vom Lehrer gewünscht, benotet werden. Man könnte aber anstelle einer Präsentation auch eine Art 
Dokumentation der Arbeit veranlassen und benoten, dies ist dem Lehrer überlassen. Eine Rückmeldung des Events an die Verantwortlichen von 
OpenSchoolMaps wäre aucht toll, damit wir uns verbessern können und auch in Zukunft tolle Lerninhalte veröffentlichen können.
