= Die Umgebung selber kartografieren - Outdoor Mapping Event
OpenSchoolMaps.ch -- Freie Lernmaterialien zu freien Geodaten und Karten
:xrefstyle: short
:imagesdir: ../../bilder/
include::../../snippets/lang/de.adoc[]
include::../../snippets/suppress_title_page.adoc[]

Eine Anleitung für Lehrpersonen und Instruktoren

== Übersicht

.Ziel
Das Ziel dieses Arbeitsblattes ist es, Lehrpersonen und Instruktoren einen Überblick zu verschaffen 
wie man erfolgreich ein Outdoor Mapping Event für die Schülerinnen und Schüler einer Klasse durchführt.

.Zielgruppe
Lehrpersonen und Instruktoren

.Zeitplanung
Die Bearbeitung dieses Arbeitsblatts verlangt je nach Vorkenntnissen unterschiedlich viel Zeit.

.Aufbau
Folgende Themen werden behandelt:

* Einleitung
* Checkliste
* Vorbereitung
* Den Event auswerten und Abschluss des Events 

== Einleitung

Technologie ist immer weniger aus dem Alltag der Menschen zu denken, dazu gehören auch Onlin-Kartendienste. Besonders junge Leute, die sich 
nicht sehr viel mit Informatik beschäftigen, kennen fast nur Google Maps. Dabei gibt es ganz viele Alternativen dazu, eine ganz besondere 
ist OpenStreetMap. Der Vorteil von OpenStreetMap ist, dass die Daten den Nutzern (der Community) gehören und nicht einer Unternehmung oder 
einer Regierungsbehörde. Dies setzt aber auch vorraus, dass die Daten durch die Nutzer ergänzt und aktuell gehalten werden. Doch Kartografieren 
an sich ist weder langweilig noch schwierig, darum sollte es jeder können. Eine Möglichkeit das Kartografieren bekannter zu machen, ist es in den 
Unterricht einzubinden, beispielsweise im Geografie- oder Geschichtsunterricht. Ein Outdoor Mapping Event soll einen ersten Einblick geben.

Die unten abgebildete Checkliste beinhaltet eine kurze Auflistung der Themen, die wichtig sind um einen erfolgreichen Event lancieren zu können. 
Auf die aufgelisteten Themen wird Abschnitt für Abschnitt näher eingegangen.

== Checkliste

* Studium der Unterlagen
* Durchführung eines Testlaufs
* Integrieren der Daten in OSM
* Einführung zur Thematik für die Schülerinnen und Schüler
* Vorbereitung
* Den Event auswerten und Abschluss des Events 

== Studium der Unterlagen

Bevor Sie ein erfolgreiches Outdoor Mapping Event durchführen können, müssen Sie sich mit der Thematik befassen. Es wäre gut, wenn Sie einige Wochen 
im Vorraus die OpenSchoolMaps-Unterlagen zur Hand nehmen und diese studieren. Die Unterlagen beinhalten sowohl Theorie wie auch Aufgaben zum Lösen. 
Seien Sie auf mögliche Fragen der Schülerinnen und Schüler vorbereitet und machen Sie sich so viele Notizen wie es nur geht. Wenn Ihnen etwas nicht ganz 
klar ist, können Sie entweder jemand zur Hilfe nehmen oder im Internet nach Antworten suchen, da die OSM-Community sehr gross ist. Dennoch denke ich sollte 
das studieren der Unterlagen nicht sehr schwierig sein und gut im Selbststudium machbar sein.

== Durchführung eines Testlaufs

Zu einer guten Vorbereitung gehört nicht nur das Studieren der Unterlagen, sondern auch das Durchführen eines Testlaufs. Gehen Sie am Wochenende oder 
nach Unterrichtsschluss auf einen Spaziergang und Wenden Sie ihr neu erworbenes Wissen der Unterlagen auf ihre Umgebung an. Erkunden Sie die Umgebung 
aus Sicht eines Kartografierers.

== Integrieren der Daten in OSM

== Einführung zur Thematik für die Schülerinnen und Schüler

== Vorbereitung

Die Klasse sollte zur Durchführung des Events Zweiergruppen bilden. Dies macht es sowohl für die Schülerinnen und Schüler spannender 
als auch für die Lehrperson einfacher zu Organisieren. Pro Zweiergruppe sollte ein Android-Smartphone vorhanden sein (wird wahrscheinlich 
kein Problem sein in der heutigen Zeit) mit der App "OSMTracker for Android". Zudem sollte ein Raum zur Verfügung stehen mit genügend PCs 
und/oder Laptops mit Zugang zum Internet, um auf OpenStreetMap.org die gesammelten Daten zu integrieren. Anstelle eines Smartphones kann 
auch mit Stift und Papier gearbeitet werden. Auf dem Papier sollte dann die Umgebung abgebildet sein, die es zu erkunden gilt. Nicht zwingend 
aber dennoch sinnvoll wäre schönes Wetter, da es eine Outdoor-Aktivität ist. Deshalb sollte nicht allzu stark im Voraus geplant werden. 

Zuletzt sollte unbedingt das Erkundungsgebiet vom Lehrer (oder in der Klasse) eingegrenzt werden, damit die Schülerinnen und Schülern nicht 
allzu grosse Distanzen gehen, unnötig Zeit verloren geht und das Wesentliche aus den Augen verloren geht. Zusätzlich wäre es auch noch sinnvoll, 
das Erkundungsgebiet in kleinere Gebiete einzuteilen und den Gruppen zuzuweisen, damit möglichst wenige Routen mehrmals kartografiert werden.


CAUTION: Achten Sie darauf, dass Sie genug Lektionen einplanen. Kartografieren kann länger dauern als man denkt, deshalb planen Sie grosszügig!

== Den Event auswerten und Abschluss des Events 

Am Schluss des Events sollen die Schülerinnen und Schüler ihre Ergebnisse auswerten und der Klasse präsentieren. 
Das Auswerten kann entweder jeder für sich oder pro Zweiergruppe geschehen. Zum Auswerten gehören Vorher-Nachher-Vegleiche 
der Kartenausschnitte, statistische Auswertungen und die persönliche Reflexion. Nach dem Auswerten des Events und den Präsentationen 
der Ergebnisse wäre es auch noch sinnvoll, innerhalb der ganzen Klasse ein Fazit zu ziehen. Was war gut? Was war nicht so gut? Was kann 
man nächstes Mal besser machen? Was hat die Klasse gelernt? Diese Feststellungen sollten unbedingt in einem Bericht festgehalten werden.

Die Präsentationen können natürlich, falls vom Lehrer gewünscht, benotet werden. Man könnte aber anstelle einer Präsentation auch eine Art 
Dokumentation der Arbeit veranlassen und benoten, dies ist dem Lehrer überlassen. Eine Rückmeldung des Events an die Verantwortlichen von 
OpenSchoolMaps wäre aucht toll, damit wir uns verbessern können und auch in Zukunft tolle Lerninhalte veröffentlichen können.
